version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: rl-demo
        container_name: rl-demo
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - app-network
        depends_on:
            - db


    webserver:
        image: nginx:alpine
        container_name: rl-demo-webserver
        restart: unless-stopped
        ports:
            - "8080:8080"
            - "443:443"
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app-network

    db:
        image: mysql:8.2.0
        container_name: rl-demo-mysql
        restart: unless-stopped
        ports:
            - "${DB_PORT}:${DB_PORT}"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
